### ISSUE TITLE
informetion

### ISSUE THREAD

**Issue by Eldon1411** [Akm-infosec/blackhat#1]
am looking direct contact informetion for glotv.me

please healp

**Comment by Eldon1411** [comment]
will pay for it if anyone provide thier direct informetion..

**Comment by tomsingh** [comment]
I can help

**Comment by tomsingh** [comment]
> am looking direct contact informetion for glotv.me
> 
> 
> 
> please healp

Dm me

**Comment by Eldon1411** [comment]
Please email me at ***@***.***

**Comment by tomsingh** [comment]
Hello how are you ?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
